### ISSUE TITLE
Set status state rather then is submitting 

### ISSUE THREAD

**Issue by isaac-martin** [formspark/use-formspark#6]
I am happy to make this contribution, but just wanted to check if it makes sense before i open the PR
Change the submitting state variable to be an enum 
```jsx
"submitting" | "success" | "error" 
```

would maybe want somewhere to put the error text as well that can be access via the hook?

**Comment by botre** [comment]
Hello,

Thank you for reaching out,
I would like to avoid introducing a breaking change.

I'm open to something like this, however: 

```typescript
const [submit, submitting, submitted, error] = useFormspark({
    formId: "your-form-id"
});
```

**Comment by isaac-martin** [comment]
Yeah that also works. I'm sure most people are doing something similar to this - so maybe i might just update the docs?
That way people can do what they need with the error that gets thrown?
```jsx
  const onSubmit = async (evt) => {
    evt.preventDefault();

    submit(formValue )
      .then(() => setFormStatus('success'))
      .catch(() => setFormStatus('error'));
  };
```

**Comment by botre** [comment]
Yup that makes sense 👍
