### ISSUE TITLE
Internal server Error | Captcha options

### ISSUE THREAD

**Issue by matgott** [formspark/use-formspark#7]
Hi, I'm trying to use this hook but developing locally I get INTERNAL SERVER ERROR and header x-cache: Error from cloudfront when I tried to submit the POST request.

And also, we don't have any property to send the hCaptcha, reCaptchat, etc.

**Comment by botre** [comment]
Hello,

Can you send a snippet of your code, please?

**Comment by botre** [comment]
Closing this, since you already opened an issue here: https://github.com/formspark/documentation/issues/101
Captcha properties are simply to be sent along in the body.
