### ISSUE TITLE
With React 18, npm install fails without --force

### ISSUE THREAD

**Issue by ashour** [formspark/use-formspark#8]
Just upgraded a NextJS app to React 18, and I could no longer build the app with `npm install` without using `npm install --force`. The issue seems to be use-formspark requiring React 16.8 or 17 as a peer dependency. When I did use `--force` everything stalled and worked fine, so you might just need to update your React version dependencies without too much change.

**Comment by botre** [comment]
Hello,

Thank you for reporting this!

Version 0.1.39 is now on NPM, this version supports React 18.

Cheers,

**Comment by ashour** [comment]
Thank you for taking care of it so quickly :)

Mohammad Ashour
